apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8sdiscovery
subjects:
  - kind: ServiceAccount
    name: k8sdiscovery
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: k8sdiscovery
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8sdiscovery
  labels:
    k8s-app: k8sdiscovery
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources:
      - namespaces
      - pods
      - nodes
    verbs:
      - get
      - watch
      - list
  - apiGroups: ["apps"]
    resources:
      - replicasets
    verbs: ["get", "list", "watch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8sdiscovery
  namespace: kube-system
  labels:
    k8s-app: k8sdiscovery
---
apiVersion: v1
kind: Pod
metadata:
  name: k8sdiscovery
  namespace: kube-system
  labels:
    role: profiling
spec:
  serviceAccountName: k8sdiscovery
  containers:
    - name: k8sdiscovery
      #imagePullPolicy: Never
      image: docker.io/chrismark/k8sdiscovery:v0.0.2
      command: ["./k8sdiscovery"]